#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - unzip
  - htop
  - git
  - net-tools
  - docker.io
  - kubectl
  - vim

runcmd:
  - echo "System setup completed" | logger