#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - unzip
  - htop

# Mount the data disk for Ollama models
disk_setup:
  /dev/sdc:
    table_type: gpt
    layout: true

fs_setup:
  - label: ollama-models
    filesystem: ext4
    device: /dev/sdc1

mounts:
  - ["/dev/disk/by-label/ollama-models", "/opt/ollama-models", "ext4", "defaults", "0", "2"]

runcmd:
  # Create ollama user and group
  - useradd -r -s /bin/false -d /opt/ollama ollama
  
  # Create directories and set permissions
  - mkdir -p /opt/ollama /opt/ollama-models
  - chown ollama:ollama /opt/ollama /opt/ollama-models
  
  # Install Ollama
  - curl -fsSL https://ollama.com/install.sh | sh
  
  # Create systemd service override to use data disk
  - mkdir -p /etc/systemd/system/ollama.service.d
  - |
    cat > /etc/systemd/system/ollama.service.d/override.conf << 'EOF'
    [Service]
    Environment="OLLAMA_MODELS=/opt/ollama-models"
    Environment="OLLAMA_HOST=0.0.0.0:11434"
    EOF
  
  # Enable and start Ollama service
  - systemctl daemon-reload
  - systemctl enable ollama
  - systemctl start ollama
  
  # Wait for service to be ready
  - sleep 10
  
  # Download a lightweight model for testing
  - sudo -u ollama OLLAMA_MODELS=/opt/ollama-models /usr/local/bin/ollama pull llama3.2:1b

write_files:
  - path: /etc/logrotate.d/ollama
    content: |
      /var/log/ollama/*.log {
          daily
          rotate 7
          compress
          delaycompress
          missingok
          notifempty
          create 644 ollama ollama
      }