#cloud-config
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - jq
  - python3
  - python3-pip
  - unzip
  - apt-transport-https
write_files:
  - path: /etc/sysctl.d/99-ragflow.conf
    owner: root:root
    permissions: '0644'
    content: |
      vm.max_map_count=262144
  - path: /etc/systemd/system/ollama.service.d/override.conf
    owner: root:root
    permissions: '0644'
    content: |
      [Service]
      Environment="OLLAMA_HOST=0.0.0.0"
runcmd:
  - sysctl -p /etc/sysctl.d/99-ragflow.conf
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - |
      bash -lc 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) stable" > /etc/apt/sources.list.d/docker.list'
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker ${admin_username}
  - systemctl enable docker
  - systemctl restart docker
  - curl -fsSL https://ollama.ai/install.sh | sh
  - systemctl daemon-reload
  - systemctl enable ollama
  - systemctl restart ollama
  - |
      if [ ! -d /opt/ragflow ]; then
        git clone --depth 1 https://github.com/infiniflow/ragflow.git /opt/ragflow
      else
        cd /opt/ragflow && git fetch --all --tags && git reset --hard origin/${ragflow_branch}
      fi
  - chown -R ${admin_username}:${admin_username} /opt/ragflow
  - |
      bash -lc 'cd /opt/ragflow && git checkout ${ragflow_branch}'
  - |
      bash -lc 'cd /opt/ragflow && git pull origin ${ragflow_branch}'
  - |
      bash -lc 'cd /opt/ragflow/docker && sed -i "s#^RAGFLOW_IMAGE=.*#RAGFLOW_IMAGE=${ragflow_image}#" .env'
  - |
      bash -lc 'cd /opt/ragflow/docker && docker compose -f docker-compose.yml pull'
  - |
      bash -lc 'cd /opt/ragflow/docker && docker compose -f docker-compose.yml up -d'
%{ for model in ollama_models ~}
  - sudo -u ${admin_username} bash -lc 'OLLAMA_HOST=0.0.0.0 ollama pull ${model}'
%{ endfor ~}
  - systemctl restart ollama
  - echo "Ragflow setup finished" > /var/log/ragflow-setup.log
